#!/usr/bin/env sh

# Shared settings for Bash and Zsh

# Allows moving between words with ctrl+left,ctrl+right
# Find key sequences by entering read and replacing ^[ with \e
if [ -n "$ZSH_VERSION" ]; then
    # Zsh syntax
    bindkey "\e[1;5C" forward-word
    bindkey "\e[1;5D" backward-word
elif [ -n "$BASH_VERSION" ]; then
    # Bash syntax
    bind '"\e[1;5C": forward-word'
    bind '"\e[1;5D": backward-word'
fi
